# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt3.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("WTH")
        MainWindow.resize(330, 80)
        MainWindow.setMinimumSize(QtCore.QSize(330, 80))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 80))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/x3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
      
        MainWindow.setStyleSheet("background-color:rgb(45, 45, 45);\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMinimumSize(QtCore.QSize(0, 30))
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(50, 30))
        self.frame_toggle.setStyleSheet("QFrame{\n"
"background-color: rgb(81, 187, 168);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"background-color: rgb(18, 209, 197);\n"
"}\n"
"\n"
"\n"
"")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_wth = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_wth.sizePolicy().hasHeightForWidth())
        self.btn_wth.setSizePolicy(sizePolicy)
        self.btn_wth.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:0px solid;\n"
"background-color: transparent;\n"
"\n"
"\n"
"\n"
"")
        self.btn_wth.setIcon(icon)
        self.btn_wth.setObjectName("btn_wth")
        self.verticalLayout_2.addWidget(self.btn_wth)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
         
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.frame_top.setStyleSheet(
"background-color:transparent;\n"
"border:none;\n"
"")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_menu_1 = QtWidgets.QPushButton(self.frame_top)
        self.btn_menu_1.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_menu_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_menu_1.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border:0px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(45, 45, 45);\n"
"    color: rgb(50, 190, 166);\n"

"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: rgb(59, 59, 59);\n"
"}")
        icon1 = QtGui.QIcon()
        
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_1.setIcon(icon1)
        self.btn_menu_1.setObjectName("btn_menu_1")
        self.horizontalLayout_3.addWidget(self.btn_menu_1)
        self.btn_menu_2 = QtWidgets.QPushButton(self.frame_top)
        self.btn_menu_2.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_menu_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_menu_2.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border:0px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(45, 45, 45);\n"
"    color: rgb(50, 190, 166);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: rgb(59, 59, 59);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_2.setIcon(icon2)
        self.btn_menu_2.setObjectName("btn_menu_2")
        self.horizontalLayout_3.addWidget(self.btn_menu_2)
        self.btn_menu_3 = QtWidgets.QPushButton(self.frame_top)
        self.btn_menu_3.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_menu_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_menu_3.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border:0px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(45, 45, 45);\n"
"    color: rgb(50, 190, 166);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: rgb(59, 59, 59);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/save (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_3.setIcon(icon3)
        self.btn_menu_3.setObjectName("btn_menu_3")
        self.horizontalLayout_3.addWidget(self.btn_menu_3)
        self.btn_menu_4 = QtWidgets.QPushButton(self.frame_top)
        self.btn_menu_4.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_menu_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_menu_4.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(35, 35, 35);\n"
"border:0px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(45, 45, 45);\n"
"    color: rgb(50, 190, 166);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
" background-color: rgb(59, 59, 59);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu_4.setIcon(icon4)
        self.btn_menu_4.setObjectName("btn_menu_4")
        self.horizontalLayout_3.addWidget(self.btn_menu_4)
        self.horizontalLayout.addWidget(self.frame_top, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left = QtWidgets.QFrame(self.Content)
        self.frame_left.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_left.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_left.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_left)
        self.frame.setMinimumSize(QtCore.QSize(20, 20))
        self.frame.setMaximumSize(QtCore.QSize(20, 20))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("border-image: url(:/icon/icons/i button.png);\n"
"background-color:transparent;\n"
"border:none;\n"
"")
        self.btn_info = QtWidgets.QPushButton(self.frame)
        self.btn_info.setGeometry(QtCore.QRect(0, 0, 20, 20))
        self.btn_info.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_info.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_info.setStyleSheet("border-image: url(:/icon/icons/i button.png);\n"
"background-color:transparent;\n"
"border:none;\n"
"")
        self.btn_info.setText("")
        self.btn_info.setObjectName("btn_info")
        self.verticalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_left)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setMinimumSize(QtCore.QSize(0,50))
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_pages)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_pages)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setStyleSheet("color: rgb(119, 221, 0);")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_pages)
        self.lineEdit.setStyleSheet("border:none;\n"
"background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.btn_add_note = QtWidgets.QPushButton(self.frame_pages)
        self.btn_add_note.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_add_note.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_add_note.setStyleSheet("#btn_add_note{\n"
"background-color:transparent;\n"
"border-image: url(:/icon/icons/plus16.png);\n"
"}\n"
"\n"
"\n"
"#btn_add_note:pressed{\n"
"background-color:transparent;\n"
"border-image: url(:/icon/icons/plus.png);\n"
"}\n"
"")
        self.btn_add_note.setText("")
        self.btn_add_note.setObjectName("btn_add_note")
        self.horizontalLayout_4.addWidget(self.btn_add_note)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addWidget(self.frame_pages, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WTH"))
        self.btn_wth.setText(_translate("MainWindow", "WTH"))
        self.btn_menu_1.setText(_translate("MainWindow", "Start"))
        self.btn_menu_2.setText(_translate("MainWindow", "Shot"))
        self.btn_menu_2.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.btn_menu_3.setText(_translate("MainWindow", "Save"))
        self.btn_menu_4.setText(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow", "Welcome, hit Start button before taking screen shot."))
import icon
